DEFAULT_MAX_SUBMISSION_ATTEMPTS = 5

LEARNING_TASK_POINTS = 35
CODING_TASK_POINTS = 65
BUILD_TASK_POINTS = 100

DAILY_STREAK_REQUIRED_POINTS = 100
DAILY_STREAK_BONUS_THRESHOLD = 300
MAX_EXTRA_STREAK_DAYS_PER_DAY = 1

PARTIAL_REWARD_LOW = 0.6
PARTIAL_REWARD_HIGH = 0.75

FREE_ACTIVE_GOALS_LIMIT = 1

MAX_TASK_DIFFICULTY = 5
MIN_TASK_DIFFICULTY = 1
