from app.domain.languages import (
    FREE_LANGUAGES,
    STARTER_LANGUAGES,
    PLUS_LANGUAGES,
)
SUBSCRIPTION_CONFIG = {
    "free": {
        "max_active_goals": 1,
        "daily_tasks_min": 2,
        "daily_tasks_max": 4,
        "max_daily_points": 135,
        "ai_level": "basic",
        "weakness_map": False,
        "adaptive_difficulty": False,
        "hardcore_allowed": False,
        "ai_requests_per_day": 20,
        "ai_coach_enabled": False,
        "precheck_enabled": False,
        "adaptive_tasks_enabled": False,
        "allowed_languages": FREE_LANGUAGES,
        "custom_language_allowed": False,
        "quiz_generations_per_day": 3,
        
    },
    "starter": {
        "max_active_goals": 1,
        "daily_tasks_min": 4,
        "daily_tasks_max": 7,
        "max_daily_points": 250,
        "ai_level": "improved",
        "weakness_map": True,
        "adaptive_difficulty": False,
        "hardcore_allowed": False,
        "ai_requests_per_day": 50,
        "ai_coach_enabled": False,
        "precheck_enabled": True,
        "adaptive_tasks_enabled": False,
        "allowed_languages": STARTER_LANGUAGES,
        "custom_language_allowed": False,
        "quiz_generations_per_day": 6,
    },
    "plus": {
        "max_active_goals": 3,
        "daily_tasks_min": 10,
        "daily_tasks_max": 15,
        "max_daily_points": 400,
        "ai_level": "advanced",
        "weakness_map": True,
        "adaptive_difficulty": True,
        "hardcore_allowed": False,
        "ai_requests_per_day": 110,
        "ai_coach_enabled": True,
        "precheck_enabled": True,
        "adaptive_tasks_enabled": True,
        "allowed_languages": PLUS_LANGUAGES,
        "custom_language_allowed": False,
        "quiz_generations_per_day": 9,
    },
    "ultra": {
        "max_active_goals": 5,
        "daily_tasks_min": 15,
        "daily_tasks_max": 25,
        "max_daily_points": 600,
        "ai_level": "elite",
        "weakness_map": True,
        "adaptive_difficulty": True,
        "hardcore_allowed": True,
        "ai_requests_per_day": 250,
        "ai_coach_enabled": True,
        "precheck_enabled": True,
        "adaptive_tasks_enabled": True,
        "allowed_languages": ["*"],
        "custom_language_allowed": True,
        "quiz_generations_per_day": 12,
    },
}
