"""add subscription expires and beta tester

Revision ID: 04e0078f2bb6
Revises: cd5964b07dba
Create Date: 2026-05-16 02:04:28.993716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e0078f2bb6'
down_revision: Union[str, Sequence[str], None] = 'cd5964b07dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'subscription_expires_at',
            sa.DateTime(timezone=True),
            nullable=True,
        )
    )
    op.add_column(
        'users',
        sa.Column(
            'beta_tester',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'beta_tester')
    op.drop_column('users', 'subscription_expires_at')
    # ### end Alembic commands ###
