"""add today verified points

Revision ID: 148576596388
Revises: d07eadf6d55d
Create Date: 2026-05-10 22:12:39.821984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '148576596388'
down_revision: Union[str, Sequence[str], None] = 'd07eadf6d55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_attempts')
    op.add_column(
        'user_streaks',
        sa.Column(
            'today_verified_points',
            sa.Integer(),
            nullable=False,
            server_default='0',
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_streaks', 'today_verified_points')
    op.create_table('exam_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attempt_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('earned_points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=40), server_default=sa.text("'pending_review'::character varying"), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suspicion_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followup_question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('affects_streak', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('manual_review_requested', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('exam_attempts_goal_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('exam_attempts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('exam_attempts_pkey'))
    )
    # ### end Alembic commands ###
