"""add polar subscription id

Revision ID: 4565ca239d4b
Revises: 04e0078f2bb6
Create Date: 2026-05-18 22:04:17.385265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4565ca239d4b'
down_revision: Union[str, Sequence[str], None] = '04e0078f2bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('polar_subscription_id', sa.String(), nullable=True))
    op.alter_column('users', 'beta_tester',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'beta_tester',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('users', 'polar_subscription_id')
    # ### end Alembic commands ###
