"""create notifications table

Revision ID: 90e0a9c966bc
Revises: c9ec02692ffb
Create Date: 2026-05-10 22:52:27.447037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90e0a9c966bc'
down_revision: Union[str, Sequence[str], None] = 'c9ec02692ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('exam_attempts', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.add_column('exam_attempts', sa.Column('attempt_type', sa.String(length=20), nullable=False))
    op.add_column('exam_attempts', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('exam_attempts', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exam_attempts', 'suspicion_score',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('exam_attempts', 'affects_streak',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('exam_attempts', 'manual_review_requested',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('exam_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('exam_attempts_user_id_fkey'), 'exam_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'exam_attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exam_attempts', 'goals', ['goal_id'], ['id'], ondelete='SET NULL')
    op.drop_column('exam_attempts', 'exam_title')
    op.alter_column('user_streaks', 'today_verified_points',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_streaks', 'today_verified_points',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.add_column('exam_attempts', sa.Column('exam_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exam_attempts', type_='foreignkey')
    op.drop_constraint(None, 'exam_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('exam_attempts_user_id_fkey'), 'exam_attempts', 'users', ['user_id'], ['id'])
    op.alter_column('exam_attempts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exam_attempts', 'manual_review_requested',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('exam_attempts', 'affects_streak',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('exam_attempts', 'suspicion_score',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('exam_attempts', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('exam_attempts', 'reviewed_at')
    op.drop_column('exam_attempts', 'attempt_type')
    op.drop_column('exam_attempts', 'goal_id')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
