"""add polar subscription cancel fields

Revision ID: f173ccb2d54e
Revises: 4565ca239d4b
Create Date: 2026-05-18 23:54:40.296968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f173ccb2d54e'
down_revision: Union[str, Sequence[str], None] = '4565ca239d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "users",
        sa.Column(
            "polar_subscription_cancel_at_period_end",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "polar_subscription_current_period_end",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'polar_subscription_current_period_end')
    op.drop_column('users', 'polar_subscription_cancel_at_period_end')
    # ### end Alembic commands ###
